spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/menudb
    # log4j2? ???? ?? ?? ????? jdbc ? ??? ?? ??
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp