spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/menudb
    # log4j2를 사용 하고 싶을때 driver-class-name 와 jdbc-url을 아래와 같이 수정
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

# fatal -> error -> warn -> info -> debug -> trace
# fatal : 애플리케이션이 동작하지 않는 아주 심각한 경우
# error : 요청 처리 중 문제 발생
# warn : 처리 가능하지만 향후 시스템 에러의 원인 가능
# debug : 개발 시 디버그 용도로 사용한 메시지
# trace : 디버그 레벨이 광범위할 경우 좀 더 상세한 상태
logging:
  level:
#    root: debug
    com:
      ohgiraffers:
        mybatisspring:
          section01:
            factorybean: debug